"""Initial migration

Revision ID: 09157c5435aa
Revises: 942035b2fbc8
Create Date: 2025-01-13 12:44:09.409267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '09157c5435aa'
down_revision: Union[str, None] = '942035b2fbc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_main_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('developer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('games_static_info',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('players_total', sa.Integer(), nullable=True),
    sa.Column('players_online', sa.Integer(), nullable=True),
    sa.Column('production_date', sa.Date(), nullable=True),
    sa.Column('current_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games_main_info.id'], ),
    sa.PrimaryKeyConstraint('game_id'),
    sa.UniqueConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games_static_info')
    op.drop_table('games_main_info')
    # ### end Alembic commands ###
