components:
  schemas:
    AUTH_api_token:
      properties:
        api_token:
          title: Api Token
          type: string
      title: AUTH_api_token
      type: object
    GAMES_list_return:
      properties:
        games:
          items:
            $ref: '#/components/schemas/GAME_short_data_return'
          title: Games
          type: array
        offset:
          default: 0
          title: Offset
          type: integer
        total:
          default: 0
          title: Total
          type: integer
      title: GAMES_list_return
      type: object
    GAME_full_data_return:
      properties:
        current_version:
          anyOf:
          - type: string
          - type: 'null'
          title: Current Version
        developer:
          anyOf:
          - type: string
          - type: 'null'
          title: Developer
        game_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Game Id
        genre:
          anyOf:
          - type: string
          - type: 'null'
          title: Genre
        id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Id
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
        platform:
          anyOf:
          - type: string
          - type: 'null'
          title: Platform
        players_online:
          anyOf:
          - type: integer
          - type: 'null'
          title: Players Online
        players_total:
          anyOf:
          - type: integer
          - type: 'null'
          title: Players Total
        production_date:
          anyOf:
          - format: date
            type: string
          - type: 'null'
          title: Production Date
        stars:
          anyOf:
          - type: integer
          - type: 'null'
          title: Stars
      title: GAME_full_data_return
      type: object
    GAME_short_data_return:
      properties:
        genre:
          anyOf:
          - type: string
          - type: 'null'
          title: Genre
        id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Id
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
      title: GAME_short_data_return
      type: object
    GAME_success_addeded_main_data:
      properties:
        game_id:
          title: Game Id
          type: integer
        game_name:
          title: Game Name
          type: string
        status:
          default: Game was added.
          title: Status
          type: string
      title: GAME_success_addeded_main_data
      type: object
    GAME_success_addeded_static_info:
      properties:
        current_version:
          anyOf:
          - type: string
          - type: 'null'
          description: 'Recomended format: vN.M: N - major ver, M - minor ver.'
          title: Current Version
        game_id:
          title: Game Id
          type: integer
        players_online:
          anyOf:
          - type: integer
          - type: 'null'
          title: Players Online
        players_total:
          anyOf:
          - type: integer
          - type: 'null'
          title: Players Total
        production_date:
          anyOf:
          - format: date
            type: string
          - type: 'null'
          description: 'Data format: yyyy-mm-dd. Separator: -'
          title: Production Date
        stars:
          anyOf:
          - type: integer
          - type: 'null'
          title: Stars
        status:
          default: Static data was succesed added.
          title: Status
          type: string
      required:
      - game_id
      title: GAME_success_addeded_static_info
      type: object
    GameGenre:
      enum:
      - Arcade
      - Clicker
      - Slasher
      - Simulation
      - Puzzle
      - Battle Royale
      - Platformer
      - Word
      - Trivia
      - Runner
      - Action
      - Time Management
      - Survival
      title: GameGenre
      type: string
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    Platform:
      enum:
      - iOS
      - Android
      title: Platform
      type: string
    USER_success_created:
      properties:
        status:
          default: User addeded.
          title: Status
          type: string
        uuid:
          format: uuid
          title: Uuid
          type: string
      title: USER_success_created
      type: object
    USER_uuid:
      properties:
        uuid:
          format: uuid
          title: Uuid
          type: string
      title: USER_uuid
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
  /auth/get_api_token:
    get:
      operationId: get_api_token_auth_get_api_token_get
      parameters:
      - in: query
        name: user_uuid
        required: true
        schema:
          title: User Uuid
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AUTH_api_token'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Api Token
      tags:
      - Auth
  /games/add_game:
    post:
      operationId: add_game_games_add_game_post
      parameters:
      - in: query
        name: name
        required: true
        schema:
          minLength: 3
          title: Name
          type: string
      - in: query
        name: type
        required: false
        schema:
          $ref: '#/components/schemas/GameGenre'
          default: Action
      - in: query
        name: platform
        required: false
        schema:
          $ref: '#/components/schemas/Platform'
          default: iOS
      - in: query
        name: developer
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Developer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GAME_success_addeded_main_data'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Add Game
      tags:
      - Game
  /games/add_game_static_info:
    post:
      operationId: add_game_static_info_games_add_game_static_info_post
      parameters:
      - in: query
        name: game_id
        required: true
        schema:
          title: Game Id
          type: integer
      - in: query
        name: stars
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Stars
      - in: query
        name: players_total
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Players Total
      - in: query
        name: players_online
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Players Online
      - in: query
        name: production_date
        required: false
        schema:
          anyOf:
          - format: date
            type: string
          - type: 'null'
          title: Production Date
      - in: query
        name: current_version
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Current Version
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GAME_success_addeded_static_info'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Add Game Static Info
      tags:
      - Game
  /games/get_game_full_info:
    get:
      operationId: get_game_full_info_games_get_game_full_info_get
      parameters:
      - in: query
        name: game_id
        required: true
        schema:
          title: Game Id
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GAME_full_data_return'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Game Full Info
      tags:
      - Game
  /games/get_games_list:
    get:
      operationId: get_games_list_games_get_games_list_get
      parameters:
      - in: query
        name: type
        required: true
        schema:
          $ref: '#/components/schemas/GameGenre'
      - in: query
        name: limit
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          default: 10
          title: Limit
      - in: query
        name: offset
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          default: 0
          title: Offset
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GAMES_list_return'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Games List
      tags:
      - Game
  /user/add_user:
    post:
      operationId: add_user_user_add_user_post
      parameters:
      - in: query
        name: name
        required: true
        schema:
          title: Name
          type: string
      - in: query
        name: password
        required: true
        schema:
          title: Password
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/USER_success_created'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Add User
      tags:
      - User
  /user/user_uuid:
    get:
      operationId: get_user_uuid_user_user_uuid_get
      parameters:
      - in: query
        name: name
        required: true
        schema:
          title: Name
          type: string
      - in: query
        name: password
        required: true
        schema:
          title: Password
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/USER_uuid'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get User Uuid
      tags:
      - User
