site_name: Say Games documenation
site_url: http://pynanist.xyz/doumentation
repo_url: https://github.com/Pseudolukian/saygames_test_docs
theme:
  name: material
  features:
    - navigation.tabs

nav:
  - API:
    - Endpoints:
      - Auth:
        - get_api_token: ./API/Endpoints/Auth/get_api_token.md
      - User:
        - add_user: ./API/Endpoints/User/add_user.md
        - user_uuid: ./API/Endpoints/User/user_uuid.md
      - Game:
        - add_game: ./API/Endpoints/Game/add_game.md
        - add_game_static_info: ./API/Endpoints/Game/add_game_static_info.md
        - get_game_full_info: ./API/Endpoints/Game/get_game_full_info.md
        - get_games_list: ./API/Endpoints/Game/get_games_list.md
      

plugins:
  - search
  - neoteroi.mkdocsoad:
      use_pymdownx: true

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
